
version: '3.9'
services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-db-container
    environment:
      - ORACLE_PASSWORD=admin123
      - ORACLE_ALLOW_REMOTE=true
    ports:
      - '1521:1521'
      - '5500:5500'
    volumes:
      - oracle-data:/opt/oracle/oradata
    networks:
      - oracle-network

volumes:
  oracle-data:

networks:
  oracle-network: